### PR TITLE
New fast JSON parser

### PR DESCRIPTION
**Pull request by michelemottini**
Adds a new JSON parser based on Microsoft's [JsonSerializer](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/how-to?pivots=dotnet-6-0).

It is 8 to10 times faster than the old one, and uses also a lot less memory (around 1/7?  . . . not sure how to measure it accurately)

Use it like this:

```
    using Hl7.Fhir.Model;
    using Hl7.Fhir.Serialization;

   . . . .

        var bundle = JsonSerializer.Deserialize<Model.R4.Bundle>(
            bundleJsonString,
            new JsonSerializerOptions().ForFhir(Model.Version.R4)
        );

```

`FromFhir()` accepts also a `ParserSettings` object (same as the old parser). 

All various overloads of [`Deserialize`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserialize?view=net-6.0)  (and [`DeserializeAsync`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserializeasync?view=net-6.0)) can be used.  

Differences with the old parser:

- Throws a `JsonException` instead of a `FormatException` on invalid input. `JsonException` includes the path of the error, something that was not available in the old parser. The library defines a `JsonException.ToFormatException()` extension method that converts `JsonException` to the old-style `FormatException`.

- Does not accept JSON using single quotes to delimit property names and strings.

- Does not accept special characters in JSON strings (e.g. new lines) - all special characters must be properly quoted

### CODE REVIEW

**Review by melissaBenzie — APPROVED** [review]
just one suggestion, add a few more fast json parsing round trip tests (json format) with different resource types and/or complex data types.  Perhaps grab a few json examples from the fhir site.

**Comment by melissaBenzie** [comment]
@scottfavre, fyi

**Comment by scottfavre** [comment]
Excellent! Thanks!

**Comment by michelemottini** [comment]
Thanks Melissa. I added a couple of test for properties that are not handled by auto-generated code and a round trip test of a big ExplanationOfBenefit + Coverage + Patient + Practitioner bundle coming from our test server

**Pull request merged**
